# Additional examples 

## more practice examples on slicing

In [20]:
# slicing from the end: useful when you want to slice regardless of whether you know beforehand the length of your variable 
my_string = 'date: 2020 01 20'
my_string[-2:]

'20'

In [48]:
# non continuous slicing 
# to take a subset of entries that aren’t next to each other in the sequence: use step size argument
primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]
subset = primes[0:12:3]
print(subset)

subset [2, 7, 17, 29]


In [22]:
# now let's start from the second item with the same step size
subset = primes[1:12:3]
print(subset)

subset [3, 11, 19, 31]


In [23]:
# again, we don't really need to define the end of the list
subset = primes[1::3]
print(subset)

subset [3, 11, 19, 31]


In [52]:
# or if starting from the beginning, defining that is not even needed
subset = primes[::3]
print(subset)

[2, 7, 17, 29, 55]


In [44]:
len(primes)

14

Accessing (slicing) nested lists:

Since a list can contain any Python variables, it can even contain other lists.

In [59]:
x = [['pepper', 'zucchini', 'onion'],
     ['cabbage', 'lettuce', 'garlic'],
     ['apple', 'pear', 'banana']]

print(x[0])
print(x[0][0])

['pepper', 'zucchini', 'onion']
pepper


## more methods for list objects
let's try a few of the methods, aka functions, that you can see when pressing tab after the dot for a list: 

In [55]:
primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]

# removing an element
print(primes)

primes.append(55)
print(primes)

primes.pop(12) # or if the last value we could leave it empty primes.pop() 
print(primes)

primes.reverse()
print(primes)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 55]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]
[37, 31, 29, 23, 19, 17, 13, 11, 7, 5, 3, 2]


## writing equations
Let's write a polynomial with a constant term, a linear term and a quadratic term
$y = a_0 + a_1x + a_2x^2$
calculate y for:  
$a_0= 2, a_1 = 4, a_2= 7$ and $x=3$

In [15]:
# we can define a0, a1 and a2 as seperate variables, or more efficiently as a list with length 3 
x = 3
a = [2, 4, 7]
y = a[0] + a[1] * x + a[2] * x**2
print(y)

# note that we couls also write 
y = a[0] * x**0 + a[1] * x**1 + a[2] * x**2


77


## more on loops 

example similar to what we did in the main material: 


In [2]:
length = 0
for letter in 'blueberry':
    length = length + 1
    print(length)
print('This word has', length, 'letters')

1
2
3
4
5
6
7
8
9
This word has 9 letters


Use a for-loop to convert the string “hello” into a list of letters:

In [ ]:
my_list = []
for char in "hello":
    my_list.append(char)
print(my_list)

adding a value to each element of a list of integers 

remember we can't use `+` since  for lists and strings, this operator concatenates or appends. 

We can use loops to access each elemnt in the list and add the desired value to it



In [1]:
odds = [1, 3, 5, 7, 9, 11, 13, 15]
# try this: primes + [1]
#let's add 1 to our list of odds
evens = []
counter = 1 
for x in odds:
    evens = evens + [x + 1]
    counter = counter + 1
    print(counter)
    print(evens)
print(evens)
# advanced note: you could do the same thing in one line: # evens = [x + 1 for x in odds] 


2
[2]
3
[2, 4]
4
[2, 4, 6]
5
[2, 4, 6, 8]
6
[2, 4, 6, 8, 10]
7
[2, 4, 6, 8, 10, 12]
8
[2, 4, 6, 8, 10, 12, 14]
9
[2, 4, 6, 8, 10, 12, 14, 16]
[2, 4, 6, 8, 10, 12, 14, 16]


Python has a built-in function called `range` that generates a sequence of numbers. `range` can accept 1, 2, or 3 parameters.

If one parameter is given, `range` generates a sequence of that length, starting at zero and incrementing by 1. For example, range(3) produces the numbers 0, 1, 2.
If two parameters are given, `range` starts at the first and ends just before the second, incrementing by one. For example, range(2, 5) produces 2, 3, 4.
If `range` is given 3 parameters, it starts at the first one, ends just before the second one, and increments by the third one. For example, range(3, 10, 2) produces 3, 5, 7, 9.

Let's write a loop that calculates 5 ** 3 using multiplication:

In [3]:
result = 1
for number in range(0, 3):
    result = result * 5
print(result)

125


The built-in function `enumerate` takes a sequence (e.g. a list) and generates a new sequence of the same length. Each element of the new sequence is a pair composed of the index (0, 1, 2,…) and the value from the original sequence. 
Let's write the polynomial above using `enumerate`:



In [18]:
y = 0
for ind, coef in enumerate(a):
    y = y + coef * x**ind
print(y)

77


## analysing data with numpy 

In [110]:
import numpy as np
a = np.array([[2, 3, 1, 3]])
print(a.shape)
a

(1, 4)


array([[2, 3, 1, 3]])

In [111]:
b = np.array([[1, 2, 5, 9], [3, 4, 7, 1]])
print(b.shape)
b

(2, 4)


array([[1, 2, 5, 9],
       [3, 4, 7, 1]])

In [112]:
data = np.append(a, b , axis=0)
data

array([[2, 3, 1, 3],
       [1, 2, 5, 9],
       [3, 4, 7, 1]])

In [134]:
data2 = np.vstack([a,b])
data2

array([[2, 3, 1, 3],
       [1, 2, 5, 9],
       [3, 4, 7, 1]])

In [131]:
#slicing data
# first value in data
print(data[0,0])

# in the middle
print(data[1,2])

print(data[1:3,1:])

print(data[3:3, 4:4])
print(data[3:3, 4:4].shape)

print(data[3:3,:])
print(data[3:3,:].shape)

2
5
[[2 5 9]
 [4 7 1]]
[]
(0, 0)
[]
(0, 4)


In [125]:
# we can take mean in any axis
print('average across rows = ', np.mean(data, axis=0))
print('average across columns = ', np.mean(data, axis=1))

average of each columns =  [2.         3.         4.33333333 4.33333333]
average of each row =  [2.25 4.25 3.75]


In [127]:
# if we want to have a measure for one row or one column specifically, we can combine function call with slicing:
print('average of row 2 = ', np.mean(data[1, :]))

average of row 2 =  4.25
